### ISSUE TITLE
HTTP Client- SSL validation

### ISSUE THREAD

**Issue by piechpatrick** [th0th/rancher-redeploy-workload#5]
HTTP Client should has an options sslCertValidation.
In my case rancher endpoint got an private CA.
![image](https://user-images.githubusercontent.com/17184858/225441184-df851981-4e54-4033-9493-888009163d96.png)

**Comment by piechpatrick** [comment]
Could be a parameterized option
![image](https://user-images.githubusercontent.com/17184858/225442324-05fbaa9f-e051-4000-ae1e-09cb772c7647.png)

**Comment by piechpatrick** [comment]
![image](https://user-images.githubusercontent.com/17184858/225445432-27aa7428-14ef-4cd2-bdd4-e8e51d6ac564.png)

**Comment by th0th** [comment]
Looks good to me (`tls_skip_verification` suits better I think), I'd love to review and merge if you send a PR 💐
